# Generated by Django 3.1.3 on 2021-02-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='제목', max_length=300)),
                ('start', models.CharField(db_column='공지일', max_length=20)),
                ('end', models.CharField(db_column='마감일', max_length=20)),
                ('dday', models.CharField(db_column='날짜', max_length=20)),
                ('specific_id', models.CharField(db_column='기관', max_length=15)),
                ('link', models.URLField(db_column='링크')),
            ],
            options={
                'db_table': 'thinkyou',
                'managed': False,
            },
        ),
    ]
